### ISSUE TITLE
approval retest

### ISSUE THREAD

**Issue by akraievoy** [akraievoy/elw#13]

**Comment by akraievoy** [comment]
more or less workable

**Comment by akraievoy** [comment]
```
2011-11-25 11:04:23.975:WARN::/a/approve
java.lang.NullPointerException
        at elw.dao.Queries.resolveFileType(Queries.java:154)
        at elw.dao.Queries.solution(Queries.java:141)
        at elw.web.ControllerElw.wmScore(ControllerElw.java:133)
        at elw.web.AdminController.do_approve(AdminController.java:262)
```
